<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/Answer_with_subquery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
database='/content/basketball.sqlite'
conn=sqlite3.connect(database)

In [ ]:
import pandas as pd
table=pd.read_sql("""SELECT *
                    FROM sqlite_master
                    WHERE type='table';""",conn)
table

,type,name,tbl_name,rootpage,sql
0,table,Team_Attributes,Team_Attributes,2,"CREATE TABLE `Team_Attributes` (`ID`, `ABBREVI..."
1,table,Player_Salary,Player_Salary,5,"CREATE TABLE `Player_Salary` (`slugSeason`, `n..."
2,table,Draft,Draft,36,"CREATE TABLE `Draft` (`yearDraft`, `numberPick..."
3,table,Team,Team,314,"CREATE TABLE `Team` (`id`, `full_name`, `abbre..."
4,table,Player_Attributes,Player_Attributes,315,"CREATE TABLE `Player_Attributes` (`ID`, `FIRST..."
5,table,Player,Player,617,"CREATE TABLE `Player` (`id`, `full_name`, `fir..."

In [ ]:
teams=pd.read_sql("""SELECT *
                    FROM Team;""",conn)
teams

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [ ]:
team_attributes=pd.read_sql("""SELECT *
                    FROM Team_Attributes;""",conn)
team_attributes

,ID,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION,FACEBOOK_WEBSITE_LINK,INSTAGRAM_WEBSITE_LINK,TWITTER_WEBSITE_LINK
0,1610612737,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Nate McMillan,Erie Bayhawks,https://www.facebook.com/hawks,https://instagram.com/atlhawks,https://twitter.com/ATLHawks
1,1610612738,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws,https://www.facebook.com/bostonceltics,https://instagram.com/celtics,https://twitter.com/celtics
2,1610612739,CLE,Cavaliers,1970,Cleveland,Rocket Mortgage FieldHouse,20562.0,Dan Gilbert,Koby Altman,JB Bickerstaff,Canton Charge,https://www.facebook.com/Cavs,https://instagram.com/cavs,https://twitter.com/cavs
3,1610612740,NOP,Pelicans,2002,New Orleans,Smoothie King Center,,Tom Benson,Trajan Langdon,Stan Van Gundy,No Affiliate,https://www.facebook.com/PelicansNBA,https://instagram.com/pelicansnba,https://twitter.com/PelicansNBA
4,1610612741,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Arturas Karnisovas,Billy Donovan,Windy City Bulls,https://www.facebook.com/chicagobulls,https://instagram.com/chicagobulls,https://twitter.com/chicagobulls
5,1610612742,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends,https://www.facebook.com/dallasmavs,https://instagram.com/dallasmavs,https://twitter.com/dallasmavs
6,1610612743,DEN,Nuggets,1976,Denver,Ball Arena,,Stan Kroenke,Tim Connelly,Michael Malone,No Affiliate,https://www.facebook.com/DenverNuggets,https://instagram.com/nuggets,https://twitter.com/nuggets
7,1610612744,GSW,Warriors,1946,Golden State,Chase Center,,Joe Lacob,Bob Myers,Steve Kerr,Santa Cruz Warriors,https://www.facebook.com/warriors,https://instagram.com/warriors,https://twitter.com/warriors
8,1610612745,HOU,Rockets,1967,Houston,Toyota Center,18104.0,Tilman Fertitta,Rafael Stone,Stephen Silas,Rio Grande Valley Vipers,https://www.facebook.com/houstonrockets,https://instagram.com/houstonrockets,https://twitter.com/HoustonRockets
9,1610612746,LAC,Clippers,1970,Los Angeles,STAPLES Center,19060.0,Steve Ballmer,Michael Winger,Tyronn Lue,Agua Caliente Clippers of Ontario,https://www.facebook.com/LAClippers,https://instagram.com/laclippers,https://twitter.com/LAClippers
10,1610612747,LAL,Lakers,1948,Los Angeles,STAPLES Center,19060.0,Jerry Buss Family Trust,Rob Pelinka,Frank Vogel,South Bay Lakers,https://www.facebook.com/losangeleslakers,https://instagram.com/lakers,https://twitter.com/Lakers
11,1610612748,MIA,Heat,1988,Miami,AmericanAirlines Arena,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce,https://www.facebook.com/MiamiHeat,https://instagram.com/miamiheat,https://twitter.com/MiamiHEAT
12,1610612749,MIL,Bucks,1968,Milwaukee,Fiserv Forum,17500.0,Wesley Edens & Marc Lasry,Jon Horst,Mike Budenholzer,Wisconsin Herd,https://www.facebook.com/milwaukeebucks,https://instagram.com/bucks,https://twitter.com/Bucks
13,1610612750,MIN,Timberwolves,1989,Minnesota,Target Center,19356.0,Glen Taylor,Scott Layden,Chris Finch,Iowa Wolves,https://www.facebook.com/MNTimberwolves,https://instagram.com/timberwolves,https://twitter.com/Timberwolves
14,1610612751,BKN,Nets,1976,Brooklyn,Barclays Center,,Joe Tsai,Sean Marks,Steve Nash,Long Island Nets,https://www.facebook.com/BrooklynNets,https://instagram.com/brooklynnets,https://twitter.com/BrooklynNets
15,1610612752,NYK,Knicks,1946,New York,Madison Square Garden,19763.0,Cablevision (James Dolan),Leon Rose,Tom Thibodeau,Westchester Knicks,https://www.facebook.com/NYKnicks,https://instagram.com/nyknicks,https://twitter.com/nyknicks
16,1610612753,ORL,Magic,1989,Orlando,Amway Center,0.0,Rick DeVos,John Hammond,Steve Clifford,Lakeland Magic,https://www.facebook.com/OrlandoMagic,https://instagram.com/orlandomagic,https://twitter.com/OrlandoMagic
17,1610612754,IND,Pacers,1976,Indiana,Bankers Life Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Nate Bjorkgren,Fort Wayne Mad Ants,https://www.facebook.com/pacers,https://instagram.com/pacers,https://twitter.com/Pacers
18,1610612755,PHI,76ers,1949,Philadelphia,Wells Fargo Center,,Joshua Harris,Elton Brand,Doc Rivers,Delaware Blue Coats,https://www.facebook.com/Sixers,https://instagram.com/sixers,https://twitter.com/Sixers
19,1610612756,PHX,Suns,1968,Phoenix,Phoenix Suns Arena,,Robert Sarver,James Jones,Monty Williams,Northern Arizona Suns,https://www.facebook.com/suns,https://instagram.com/suns,https://twitter.com/Suns
20,1610612757,POR,Trail Blazers,1970,Portland,Moda Center,19980.0,Paul Allen,Neil Olshey,Terry Stotts,No Affiliate,https://www.facebook.com/trailblazers,https://instagram.com/trailblazers,https://twitter.com/trailblazers
21,1610612758,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Monte McNair,Luke Walton,Stockton Kings,https://www.facebook.com/sacramentokings,https://instagram.com/sacramentokings,https://twitter.com/SacramentoKings
22,1610612759,SAS,Spurs,1976,San Antonio,AT&T Center,18694.0,Peter Holt,Brian Wright,Gregg Popovich,Austin Spurs,https://www.facebook.com/Spurs,https://instagram.com/spurs,https://twitter.com/spurs
23,1610612760,OKC,Thunder,1967,Oklahoma City,Chesapeake Energy Arena,,Clay Bennett,Sam Presti,Mark Daigneault,Oklahoma City Blue,https://www.facebook.com/OKCThunder,https://instagram.com/okcthunder,https://twitter.com/okcthunder
24,1610612761,TOR,Raptors,1995,Toronto,Amalie Arena,,Maple Leaf Sports and Entertainment,Masai Ujiri,Nick Nurse,Raptors 905,https://www.facebook.com/TorontoRaptors,https://instagram.com/raptors,https://twitter.com/Raptors
25,1610612762,UTA,Jazz,1974,Utah,Vivint Arena,,Ryan Smith,Dennis Lindsey,Quin Snyder,Salt Lake City Stars,https://www.facebook.com/utahjazz,https://instagram.com/utahjazz,https://twitter.com/utahjazz
26,1610612763,MEM,Grizzlies,1995,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Taylor Jenkins,Memphis Hustle,https://www.facebook.com/MemphisGrizzlies,https://instagram.com/memgrizz,https://twitter.com/memgrizz
27,1610612764,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go,https://www.facebook.com/Wizards,https://instagram.com/washwizards,https://twitter.com/WashWizards
28,1610612765,DET,Pistons,1948,Detroit,Little Caesars Arena,,Tom Gores,Ed Stefanski,Dwane Casey,Grand Rapids Drive,https://www.facebook.com/detroitpistons,https://instagram.com/detroitpistons,https://twitter.com/DetroitPistons
29,1610612766,CHA,Hornets,1988,Charlotte,Spectrum Center,19026.0,Michael Jordan,Mitch Kupchak,James Borrego,Greensboro Swarm,https://www.facebook.com/hornets,https://instagram.com/hornets,https://twitter.com/hornets

In [ ]:
result=pd.read_sql("""SELECT *
                    FROM Team_Attributes
                    WHERE ID IN (
                        SELECT id
                        FROM Team
                        WHERE state = 'New York'
                    );""",conn)
result

,ID,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION,FACEBOOK_WEBSITE_LINK,INSTAGRAM_WEBSITE_LINK,TWITTER_WEBSITE_LINK
0,1610612751,BKN,Nets,1976,Brooklyn,Barclays Center,,Joe Tsai,Sean Marks,Steve Nash,Long Island Nets,https://www.facebook.com/BrooklynNets,https://instagram.com/brooklynnets,https://twitter.com/BrooklynNets
1,1610612752,NYK,Knicks,1946,New York,Madison Square Garden,19763.0,Cablevision (James Dolan),Leon Rose,Tom Thibodeau,Westchester Knicks,https://www.facebook.com/NYKnicks,https://instagram.com/nyknicks,https://twitter.com/nyknicks